name: gan_pre
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch==2.5.1
  - torchvision==0.20.1
  - torchaudio==2.5.1
  - pytorch-cuda=11.8
  - numpy=1.26.4
  - pip:
      - insightface
      - gdown
      - onnxruntime
